config/routes.rb
Rails.application.routes.draw do
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file,
  # see http://guides.rubyonrails.org/routing.html
  resources :events, only: :show  do
    resources :tickets
    post 'tickets/create', to: 'tickets#create'
    get 'tickets/no_tickets', to: 'notickets#error'
  end

  root to: 'events#index', via: :get
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :venue
  has_many :tickets

  validates_presence_of :name, :start_at, :end_at
  validate :start_at_bigger_than_today, :end_at_bigger_than_start_at

  has_attached_file :logo
  validates_attachment_content_type :logo,
                                    content_type: %r{\Aimage\/.*\Z}

  private

  def start_at_bigger_than_today
    return unless start_at.present?
    errors.add :start_at, "can't be in the past" if start_at < Time.zone.now
  end

  def end_at_bigger_than_start_at
    return unless start_at.present? && end_at.present?
    errors.add :end_at, "must be bigger than start at" if end_at < start_at
  end
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :event

  validates :email,:number_of_tickets, presence: true
  validates_format_of :email, :with => /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/venue.rb
class Venue < ApplicationRecord
  has_many :events
  validates_presence_of :name
  validates_presence_of :address
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.where('start_at >= ?', Time.zone.now)
                   .order(start_at: :asc)
                   .limit(3)
  end

  def show
    @event = Event.find(params[:id])
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
before_action :set_event
  def new
    @ticket = Ticket.new
  end

  def show
    @ticket = Ticket.find(params[:id])
  end

  def create
    @ticket = Ticket.new(ticket_params)
    @ticket.event = @event
    if @event.number_of_tickets_available - @event.tickets_sold <= 0
      render 'events/show'
    else
      if @ticket.save
         @ticket.event.increment!(:tickets_sold, by = @ticket.number_of_tickets)
        # TicketMailer.ticket_receipt(@ticket).deliver_now
        #flash[:notice] = "Your ticket to #{@event.name} was purchased.  Please look for an email with your receipt. "
        redirect_to @ticket.event
      else
        @errors = @ticket.errors.full_messages
        render 'tickets/new', locals: { ticket: @ticket }
      end
    end
  end

  def edit
    @ticket = Ticket.find(params[:id])
  end

  def update
    @ticket = Ticket.find(params[:id])
    if @ticket.update(ticket_params)
      redirect_to root_path, notice: "Your ticket has been update!"
    else
      render :edit, alert: "Could not update your ticket!"
    end
  end

  private

  def ticket_params
    params.require(:ticket).permit(:email, :number_of_tickets)
  end

  def set_event
    @event = Event.find(params[:event_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tickets_controller_helper.rb
module TicketsControllerHelper
end

app/views/events/index.html.slim
.jumbotron
  .container
    h1.display-3 Let the exercise begin!
    p This is main page of this exercise, we will want to display upcoming events below (limited to 3).

.container
  .row
    - @events.each do |event|
      .col-md-4
        h2 = event.name
        p
          time datetime="#{event.start_at}" = l event.start_at
        p = link_to 'View details »', event_path(event), class: 'btn btn-secondary'

app/views/events/show.html.slim
.jumbotron
  .container
    = image_tag "http://res.cloudinary.com/dywzzd0as/image/upload/v1523268429/blko.svg", class: 'event-logo'
    h1.display-3 = @event.name
    p
      // NOTE should we have a helper that allow us to display the dates in
      // a different way? we could have many scenarios such as:
      //  * one day event
      //  * an event that spans between months
      //  * an event that spans between years
      //  * an event of multiple months (say what!?)
      time datetime="#{@event.start_at}" = l @event.start_at, format: '%d %B, %Y'
      '
      |-
      '
      time datetime="#{@event.end_at}" = l @event.end_at, format: '%d %B, %Y'

.container
  .row
    .col-md-8
      h2 About
      p = @event.description

      h3 Tickets Sold
      p =  @event.tickets_sold

      h3 Tickets Available
      p = @event.number_of_tickets_available - @event.tickets_sold
      - if @event.number_of_tickets_available - @event.tickets_sold <= 0
        p = link_to 'No more Tickets :(', root_path(),class: 'btn btn-secondary'
      - else
        p = link_to 'Buy Tickets »', new_event_ticket_path(@event), class: 'btn btn-secondary'
    .col-md-4
      h3 Location
      p = @event.venue.address

app/views/layouts/application.html.slim
doctype html
html
  head
    title Ruby Exercise

    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    nav.navbar.navbar-expand-md.navbar-dark.fixed-top.bg-dark
      = link_to 'Events', root_path, class: 'navbar-brand'

    main role="main"
      = yield

app/views/tickets/new.html.erb
<div class="col-xs-12">
  <%= simple_form_for ([@event, @ticket]) do |f| %>
   <%= f.error_notification %>
    <div class="container-button">
      <div class="form-inputs">
        <%= f.input :email %>
        <%= f.input :number_of_tickets %>
      </div>
      <div class="btn-medium">
        <%= f.submit 'Buy Ticket', :class => 'btn', style:"color: grey" %>
      </div>
    </div>
  <% end %>
</div>